[sections]
features = "NEW FUNCTIONALITY"
fixes = "BUG FIXES AND OTHER CHANGES TO EXISTING FUNCTIONALITY"
examples = "EXAMPLES"

[subsections]
basic = "BASIC FUNCTIONALITY"
model = "MODEL"
internal = "INTERNAL FLOW PACKAGES"
stress = "STRESS PACKAGES"
advanced = "ADVANCED STRESS PACKAGES"
solution = "SOLUTION"
exchanges = "EXCHANGES"
parallel = "PARALLEL"
netcdf = "NETCDF"

[[items]]
section = "fixes"
subsection = "stress"
description = "The default values for DENSITY\\_WATER, HEAT\\_CAPACITY\\_WATER, LATENT\\_HEAT\\_VAPORIZATION specified in the OPTIONS block were not set as indicated in the MF6IO guide.  Defaults for these three variables now set as documented in the MF6IO guide." 

[[items]]
section = "fixes"
subsection = "internal"
description = "Resolved mass-balance errors in the Central and UTVD numerical schemes caused by inconsistent interpretation of cell-to-interface distances (cl1/cl2)."