[sections]
features = "NEW FUNCTIONALITY"
fixes = "BUG FIXES AND OTHER CHANGES TO EXISTING FUNCTIONALITY"
examples = "EXAMPLES"

[subsections]
basic = "BASIC FUNCTIONALITY"
model = "MODEL"
internal = "INTERNAL FLOW PACKAGES"
stress = "STRESS PACKAGES"
advanced = "ADVANCED STRESS PACKAGES"
solution = "SOLUTION"
exchanges = "EXCHANGES"
parallel = "PARALLEL"
netcdf = "NETCDF"

[[items]]
section = "fixes"
subsection = "stress"
description = "The default values for DENSITY\\_WATER, HEAT\\_CAPACITY\\_WATER, LATENT\\_HEAT\\_VAPORIZATION specified in the OPTIONS block were not set as indicated in the MF6IO guide.  Defaults for these three variables now set as documented in the MF6IO guide." 

[[items]]
section = "fixes"
subsection = "internal"
description = "Resolved mass-balance errors in the Central and UTVD numerical schemes caused by inconsistent interpretation of cell-to-interface distances (cl1/cl2)."

[[items]]
section = "fixes"
subsection = "exchanges"
description = "When a MVR connection was included as part of an exchange between two models, it was possible to list a model name in the PACKAGES block of the MVR input file that is not one of the two models included in the exchange.  A check was added that reports an error message stating that a model name listed in the exchange MVR input file is not one of the two models connected by the exchange."

[[items]]
section = "fixes"
subsection = "model"
description = "The Flow Model Interface (FMI) package for transport and tracking models conducts TDIS compatibility checks during each stress period to ensure that the model's time discretization is compatible with that of the flow model. In particular, if a flow model stress period has just one time step, the transport or tracking model may have any number of time steps. However, if a flow model stress period has more than one time step, the transport or tracking model must have the same number of time steps. Simulations would previously stop with an error if the transport or tracking model violated this rule for any stress periods up to the simulation's last, but would not raise an error for the last stress period. The compatibility check was updated to include the last stress period. Simulations will now stop with an error if the transport or tracking model violates this rule for any stress period in the simulation."